### ISSUE TITLE
It doesn't show a captive, but rather a "no internet connection" on all apple devices

### ISSUE THREAD

**Issue by surak** [p-doyle/Micropython-DNSServer-Captive-Portal#1]
Tested on an iPad, iPhone and a Mac

**Comment by surak** [comment]
```
Incoming data...
searched domain:captive.apple.com.
Response captive.apple.com. == 10.0.0.1
b'\x96\x02\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00\x07captive\x05apple\x03com\x00\x00A\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x00<\x00\x04\n\x00\x00\x01'
Replying: captive.apple.com. -> 10.0.0.1
Incoming data...
searched domain:captive.apple.com.
Response captive.apple.com. == 10.0.0.1
b'\x05\xdc\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00\x07captive\x05apple\x03com\x00\x00\x01\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x00<\x00\x04\n\x00\x00\x01'
Replying: captive.apple.com. -> 10.0.0.1
failed handling client: function takes 2 positional arguments but 1 were given
Task exception wasn't retrieved
future: <Task> coro= <generator object 'handle_client' at 3fcc72b0>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "main.py", line 93, in handle_client
NameError: local variable referenced before assignment
Incoming data...
searched domain:_dns.resolver.arpa.
Response _dns.resolver.arpa. == 10.0.0.1
b'\xa9\xb8\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00\x04_dns\x08resolver\x04arpa\x00\x00@\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x00<\x00\x04\n\x00\x00\x01'
Replying: _dns.resolver.arpa. -> 10.0.0.1
Incoming data...
searched domain:captive.apple.com.
Response captive.apple.com. == 10.0.0.1
b'\x96\x02\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00\x07captive\x05apple\x03com\x00\x00A\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x00<\x00\x04\n\x00\x00\x01'
Replying: captive.apple.com. -> 10.0.0.1
Incoming data...
searched domain:captive.apple.com.
Response captive.apple.com. == 10.0.0.1
b'\x05\xdc\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00\x07captive\x05apple\x03com\x00\x00\x01\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x00<\x00\x04\n\x00\x00\x01'
Replying: captive.apple.com. -> 10.0.0.1
Incoming data...
searched domain:_dns.resolver.arpa.
Response _dns.resolver.arpa. == 10.0.0.1
b'\xa9\xb8\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00\x04_dns\x08resolver\x04arpa\x00\x00@\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x00<\x00\x04\n\x00\x00\x01'
Replying: _dns.resolver.arpa. -> 10.0.0.1
Timeout
Timeout
Timeout
Timeout
Timeout
Timeout
Timeout
Timeout
```

**Comment by p-doyle** [comment]
It is possible that something has changed with how Apple handles captive portals.  Unfortunately I do not have any Apple devices so am unable to do any troubleshooting.

**Comment by surak** [comment]
Can it be related to the two errors shown up there? The one about not launching the async task and the NameError exception?
